/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.Arquivo;
import static GUI.GuiQuiz.Qz;
import java.util.*;
import NEGOCIO.Avaliacao;
import NEGOCIO.Resultado;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Bernardo Gouvêa e Cesar Luis
 */
public class GuiFinal extends javax.swing.JFrame {

    /**
     * Creates new form GuiFinal
     */
    public GuiFinal() {
        initComponents();
        int maximo = GuiInicial.getMAXIMOQUESTOES() * 4;
        labelNomeAlunoFinal.setText(Avaliacao.getNome());
        labelPorcentoAproveitamento.setText(String.valueOf(Avaliacao.getAproveitamento()));
        labelQuantidadeAcertosLados.setText(String.valueOf(Qz.R.getResultadoLa()));
        labelQuantidadeAcertosAngulos.setText(String.valueOf(Qz.R.getResultadoAn()));
        labelQuantidadeAcertosPerimetro.setText(String.valueOf(Qz.R.getResultadoPe()));
        labelQuantidadeAcertosArea.setText(String.valueOf(Qz.R.getResultadoAr()));
        labelQuantidadeQuestao.setText(String.valueOf(maximo));
        labelQuantidadeAcertoQuestao.setText(String.valueOf(Avaliacao.getResult()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFinal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botaoEncerrarJogoFinal = new javax.swing.JButton();
        botaoJogarNovamente = new javax.swing.JButton();
        labelSeuAproveitamento = new javax.swing.JLabel();
        labelPorcentoAproveitamento = new javax.swing.JLabel();
        labelSeuResultado = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelQuantidadeQuestao = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelQuantidadeAcertoQuestao = new javax.swing.JLabel();
        labelAcertosPerimetro = new javax.swing.JLabel();
        labelAcertosArea = new javax.swing.JLabel();
        labelAcertosAngulos = new javax.swing.JLabel();
        labelAcertosLados = new javax.swing.JLabel();
        labelQuantidadeAcertosLados = new javax.swing.JLabel();
        labelQuantidadeAcertosAngulos = new javax.swing.JLabel();
        labelQuantidadeAcertosArea = new javax.swing.JLabel();
        labelQuantidadeAcertosPerimetro = new javax.swing.JLabel();
        labelJogoFeitoPorFinal = new javax.swing.JLabel();
        labelAlunoFinal = new javax.swing.JLabel();
        labelNomeAlunoFinal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 500));

        panelFinal.setBackground(java.awt.Color.white);
        panelFinal.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 255)));
        panelFinal.setAutoscrolls(true);
        panelFinal.setPreferredSize(new java.awt.Dimension(600, 500));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Você realizou o Quiz de Trigonometria Plana");

        botaoEncerrarJogoFinal.setText("Encerrar Jogo");
        botaoEncerrarJogoFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEncerrarJogoFinalActionPerformed(evt);
            }
        });

        botaoJogarNovamente.setText("Jogar Novamente");
        botaoJogarNovamente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoJogarNovamenteActionPerformed(evt);
            }
        });

        labelSeuAproveitamento.setText("Seu Aproveitamento:");

        labelPorcentoAproveitamento.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelPorcentoAproveitamento.setText("jLabel3");

        labelSeuResultado.setText("Seu Resultado:");

        jLabel5.setText("Das");

        labelQuantidadeQuestao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelQuantidadeQuestao.setText("jLabel6");

        jLabel7.setText("questões, você acertou");

        labelQuantidadeAcertoQuestao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelQuantidadeAcertoQuestao.setText("jLabel8");

        labelAcertosPerimetro.setText("Acertos  em questões sobre  Perímetro:");

        labelAcertosArea.setText("Acertos  em questões sobre  Área:");

        labelAcertosAngulos.setText("Acertos em questões sobre  Ângulos:");

        labelAcertosLados.setText("Acertos em questões sobre Lados:");

        labelQuantidadeAcertosLados.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelQuantidadeAcertosLados.setText("jLabel8");

        labelQuantidadeAcertosAngulos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelQuantidadeAcertosAngulos.setText("jLabel9");

        labelQuantidadeAcertosArea.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelQuantidadeAcertosArea.setText("jLabel10");

        labelQuantidadeAcertosPerimetro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelQuantidadeAcertosPerimetro.setText("jLabel11");

        labelJogoFeitoPorFinal.setText("Um jogo feito por: Bernardo Gouvêa, César Barbosa, Lucas Guilhon");

        labelAlunoFinal.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelAlunoFinal.setText("Aluno:");

        labelNomeAlunoFinal.setText("NomeAluno");

        jLabel3.setText("% de Aproveitamento");

        javax.swing.GroupLayout panelFinalLayout = new javax.swing.GroupLayout(panelFinal);
        panelFinal.setLayout(panelFinalLayout);
        panelFinalLayout.setHorizontalGroup(
            panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFinalLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFinalLayout.createSequentialGroup()
                        .addGroup(panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSeuResultado)
                            .addGroup(panelFinalLayout.createSequentialGroup()
                                .addComponent(labelAcertosArea)
                                .addGap(56, 56, 56)
                                .addGroup(panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelQuantidadeAcertosArea)
                                    .addComponent(labelQuantidadeAcertosPerimetro)
                                    .addComponent(labelQuantidadeAcertosAngulos)
                                    .addComponent(labelQuantidadeAcertosLados))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelFinalLayout.createSequentialGroup()
                        .addGroup(panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelJogoFeitoPorFinal)
                            .addGroup(panelFinalLayout.createSequentialGroup()
                                .addGroup(panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelSeuAproveitamento)
                                    .addComponent(labelAcertosLados)
                                    .addComponent(labelAcertosAngulos)
                                    .addComponent(labelAcertosPerimetro))
                                .addGap(8, 8, 8)
                                .addGroup(panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelFinalLayout.createSequentialGroup()
                                        .addComponent(labelPorcentoAproveitamento)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3))
                                    .addGroup(panelFinalLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelQuantidadeQuestao)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelQuantidadeAcertoQuestao)))))
                        .addContainerGap(176, Short.MAX_VALUE))))
            .addGroup(panelFinalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFinalLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelAlunoFinal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelNomeAlunoFinal))
                    .addGroup(panelFinalLayout.createSequentialGroup()
                        .addComponent(botaoJogarNovamente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoEncerrarJogoFinal)))
                .addContainerGap())
        );
        panelFinalLayout.setVerticalGroup(
            panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFinalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelNomeAlunoFinal)
                        .addComponent(labelAlunoFinal))
                    .addComponent(jLabel1))
                .addGap(35, 35, 35)
                .addGroup(panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSeuResultado)
                    .addComponent(jLabel5)
                    .addComponent(labelQuantidadeQuestao)
                    .addComponent(jLabel7)
                    .addComponent(labelQuantidadeAcertoQuestao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSeuAproveitamento)
                    .addComponent(labelPorcentoAproveitamento)
                    .addComponent(jLabel3))
                .addGap(47, 47, 47)
                .addGroup(panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAcertosLados)
                    .addComponent(labelQuantidadeAcertosLados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAcertosAngulos)
                    .addComponent(labelQuantidadeAcertosAngulos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAcertosPerimetro)
                    .addComponent(labelQuantidadeAcertosArea, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelQuantidadeAcertosPerimetro)
                    .addComponent(labelAcertosArea))
                .addGap(60, 60, 60)
                .addGroup(panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoJogarNovamente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoEncerrarJogoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(labelJogoFeitoPorFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFinal, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoJogarNovamenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoJogarNovamenteActionPerformed
        try {
            Arquivo.salvarQuiz(Qz);
        } catch (IOException ex) {
            Logger.getLogger(GuiFinal.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            Arquivo.salvarQuiz(Qz);
        } catch (IOException ex) {
            Logger.getLogger(GuiFinal.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            Arquivo.exportarResultado();
        } catch (IOException ex) {
            Logger.getLogger(GuiFinal.class.getName()).log(Level.SEVERE, null, ex);
        }
        GuiInicial.contador = 1;
        new GuiInicial().setVisible(true);
        dispose();

//        GuiInicial.contador = 0;
//        new GuiInicial().setVisible(true);
//        dispose();
    }//GEN-LAST:event_botaoJogarNovamenteActionPerformed

    private void botaoEncerrarJogoFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEncerrarJogoFinalActionPerformed
        //Salvar para arquivo.
        try {
            Arquivo.salvarQuiz(Qz);
        } catch (IOException ex) {
            Logger.getLogger(GuiFinal.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            Arquivo.salvarQuiz(Qz);
        } catch (IOException ex) {
            Logger.getLogger(GuiFinal.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            Arquivo.exportarResultado();
        } catch (IOException ex) {
            Logger.getLogger(GuiFinal.class.getName()).log(Level.SEVERE, null, ex);
        }
        //Tutorial para Ensino
        new GuiTutorialEnsino().setVisible(true);
        dispose();
//        Salvar para arquivo.
//        Tutorial para Ensino
//        new GuiTutorialEnsino().setVisible(true);
//        dispose();
    }//GEN-LAST:event_botaoEncerrarJogoFinalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiFinal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEncerrarJogoFinal;
    private javax.swing.JButton botaoJogarNovamente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel labelAcertosAngulos;
    private javax.swing.JLabel labelAcertosArea;
    private javax.swing.JLabel labelAcertosLados;
    private javax.swing.JLabel labelAcertosPerimetro;
    private javax.swing.JLabel labelAlunoFinal;
    private javax.swing.JLabel labelJogoFeitoPorFinal;
    private javax.swing.JLabel labelNomeAlunoFinal;
    private javax.swing.JLabel labelPorcentoAproveitamento;
    private javax.swing.JLabel labelQuantidadeAcertoQuestao;
    private javax.swing.JLabel labelQuantidadeAcertosAngulos;
    private javax.swing.JLabel labelQuantidadeAcertosArea;
    private javax.swing.JLabel labelQuantidadeAcertosLados;
    private javax.swing.JLabel labelQuantidadeAcertosPerimetro;
    private javax.swing.JLabel labelQuantidadeQuestao;
    private javax.swing.JLabel labelSeuAproveitamento;
    private javax.swing.JLabel labelSeuResultado;
    private javax.swing.JPanel panelFinal;
    // End of variables declaration//GEN-END:variables
}
