/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import NEGOCIO.*;
;
/**
 *
 * @author cesar
 */
public class GuiInicial extends javax.swing.JFrame {
    public static String auxLoginProfessor;
    public static String auxNomeAlunoInicial;
    public static String auxSenhaProfessor;
   public static int MAXIMOQUESTOES = 4;
 public static int contador = 1;
 public static Resultado R;

    public static void setContador() {
       contador++;
    }
    
    public static void setContador(int cont) {
       contador = cont;
    }
 
    public static int getMAXIMOQUESTOES() {
        return MAXIMOQUESTOES;
    }

    public GuiInicial() {
        R = new Resultado();
        initComponents();
    }

    public static int getContador() {
        return contador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelAreaProfessorInicial = new javax.swing.JLabel();
        txtLoginProfessor = new javax.swing.JTextField();
        txtSenhaProfessor = new javax.swing.JPasswordField();
        botaoEntrarProfessor = new javax.swing.JButton();
        botaoIniciarQuizInicial = new javax.swing.JButton();
        labelTituloQuizInicial = new javax.swing.JLabel();
        labelAlunoInicial = new javax.swing.JLabel();
        txtNomeAlunoInicial = new javax.swing.JTextField();
        botaoSairInicial = new javax.swing.JButton();
        labelErroSenhaProfessor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMaximumSize(new java.awt.Dimension(55, 55));

        labelAreaProfessorInicial.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelAreaProfessorInicial.setText("Área do Professor");

        txtSenhaProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaProfessorActionPerformed(evt);
            }
        });

        botaoEntrarProfessor.setText("Entrar");
        botaoEntrarProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEntrarProfessorActionPerformed(evt);
            }
        });

        botaoIniciarQuizInicial.setText("Iniciar Quiz");
        botaoIniciarQuizInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoIniciarQuizInicialActionPerformed(evt);
            }
        });

        labelTituloQuizInicial.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTituloQuizInicial.setText("QUIZ DE TRIGONOMETRIA PLANA ");

        labelAlunoInicial.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelAlunoInicial.setText("Nome do Aluno:");

        txtNomeAlunoInicial.setText("NomeAluno");
        txtNomeAlunoInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeAlunoInicialActionPerformed(evt);
            }
        });

        botaoSairInicial.setText("Sair");
        botaoSairInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairInicialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoEntrarProfessor))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(labelTituloQuizInicial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botaoSairInicial)
                            .addComponent(txtLoginProfessor)
                            .addComponent(txtSenhaProfessor)
                            .addComponent(labelAreaProfessorInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelErroSenhaProfessor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(labelAlunoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeAlunoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoIniciarQuizInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAreaProfessorInicial)
                    .addComponent(labelTituloQuizInicial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLoginProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSenhaProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoEntrarProfessor)
                .addGap(16, 16, 16)
                .addComponent(labelErroSenhaProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNomeAlunoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelAlunoInicial)
                            .addComponent(botaoIniciarQuizInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(botaoSairInicial)
                        .addGap(24, 24, 24))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoIniciarQuizInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoIniciarQuizInicialActionPerformed
        // TODO add your handling code here:
        Avaliacao.setNome(txtNomeAlunoInicial.getText());
        new GuiQuiz().setVisible(true);
        dispose();
    }//GEN-LAST:event_botaoIniciarQuizInicialActionPerformed

    private void txtSenhaProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaProfessorActionPerformed

    private void txtNomeAlunoInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeAlunoInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeAlunoInicialActionPerformed

    private void botaoSairInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairInicialActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoSairInicialActionPerformed

    private void botaoEntrarProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEntrarProfessorActionPerformed
        // TODO add your handling code here:
        auxLoginProfessor =  txtLoginProfessor.getText();
        auxSenhaProfessor=  txtSenhaProfessor.getText();
        Avaliacao.verificaAvaliador();
        if (Avaliacao.verificaAvaliador()){
       new GuiProfessor().setVisible(true);
        dispose();}
        else
            labelErroSenhaProfessor.setText("Erro de login e/ou senha");
    }//GEN-LAST:event_botaoEntrarProfessorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEntrarProfessor;
    private javax.swing.JButton botaoIniciarQuizInicial;
    private javax.swing.JButton botaoSairInicial;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelAlunoInicial;
    private javax.swing.JLabel labelAreaProfessorInicial;
    private javax.swing.JLabel labelErroSenhaProfessor;
    private javax.swing.JLabel labelTituloQuizInicial;
    private javax.swing.JTextField txtLoginProfessor;
    private javax.swing.JTextField txtNomeAlunoInicial;
    private javax.swing.JPasswordField txtSenhaProfessor;
    // End of variables declaration//GEN-END:variables
}
