/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NEGOCIO.*;

/**
 *
 * @author Bernardo Gouvêa e Cesar Luis
 */
public class GuiQuiz extends javax.swing.JFrame {

    public static double auxLadoCA, auxAreaA, auxPerim, auxAnguloC;
    public static Quiz Qz;
    public static Resultado R;

    public static double getAuxLadoCA() {
        return auxLadoCA;
    }

    public static double getAuxAreaA() {
        return auxAreaA;
    }

    public static double getAuxPerim() {
        return auxPerim;
    }

    public static double getAuxAnguloC() {
        return auxAnguloC;
    }

    /**
     * Creates new form GuiQuiz
     */
    public GuiQuiz() {
        initComponents();
        Qz = new Quiz();
        labelNomeAlunoQuiz.setText(Avaliacao.getNome());
        labelladoAB.setText(String.valueOf(Qz.Q.T.getLado(1)));
        labelladoBC.setText(String.valueOf(Qz.Q.T.getLado(2)));
        labelanguloA.setText(String.valueOf((int) Qz.Q.T.getAngulo(1)));
        labelanguloB.setText(String.valueOf((int) Qz.Q.T.getAngulo(2)));
        labelRespostaLadoCA.setText(String.valueOf(Qz.Q.T.getLado3()));
        labelRespostaAnguloC.setText(String.valueOf(Qz.Q.T.getAngulo(3)));
        labelRespostaPerimetro.setText(String.valueOf(Qz.Q.T.getPerimetro()));
        labelRespostaArea.setText(String.valueOf(Qz.Q.T.getArea()));
        labelQuestaoNumero.setText(String.valueOf(GuiInicial.getContador()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelLadoAB = new javax.swing.JLabel();
        labelLadoBC = new javax.swing.JLabel();
        labelAnguloA = new javax.swing.JLabel();
        labelAnguloB = new javax.swing.JLabel();
        labelladoAB = new javax.swing.JLabel();
        labelladoBC = new javax.swing.JLabel();
        labelanguloA = new javax.swing.JLabel();
        labelanguloB = new javax.swing.JLabel();
        labelCmLadoAB = new javax.swing.JLabel();
        labelCmLadoBC = new javax.swing.JLabel();
        labelOAnguloA = new javax.swing.JLabel();
        labelOAnguloB = new javax.swing.JLabel();
        labelDescubraValores = new javax.swing.JLabel();
        labelDadosValores = new javax.swing.JLabel();
        txtLadoCA = new javax.swing.JTextField();
        txtAnguloC = new javax.swing.JTextField();
        txtPerimetroP = new javax.swing.JTextField();
        txtAreaA = new javax.swing.JTextField();
        labelLadoCAQuiz = new javax.swing.JLabel();
        labelAnguloCQuiz = new javax.swing.JLabel();
        labelPerimetroQuiz = new javax.swing.JLabel();
        labelAreaQuiz = new javax.swing.JLabel();
        botaoProximaQuestaoQuiz = new javax.swing.JButton();
        botaoTutorialQuiz = new javax.swing.JButton();
        labelAlunoQuiz = new javax.swing.JLabel();
        labelNomeAlunoQuiz = new javax.swing.JLabel();
        botaoSairQuiz = new javax.swing.JButton();
        labelRespostaLadoCA = new javax.swing.JLabel();
        labelRespostaAnguloC = new javax.swing.JLabel();
        labelRespostaPerimetro = new javax.swing.JLabel();
        labelRespostaArea = new javax.swing.JLabel();
        labelDesenhoTriangulo = new javax.swing.JLabel();
        labelQuestaoTexto = new javax.swing.JLabel();
        labelQuestaoNumero = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 51, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(650, 500));

        labelLadoAB.setText("lado AB:");

        labelLadoBC.setText("lado BC:");

        labelAnguloA.setText("ângulo A:");

        labelAnguloB.setText("ângulo B:");

        labelladoAB.setForeground(new java.awt.Color(255, 0, 51));
        labelladoAB.setText("AB");

        labelladoBC.setForeground(new java.awt.Color(255, 0, 51));
        labelladoBC.setText("BC");

        labelanguloA.setForeground(new java.awt.Color(255, 0, 51));
        labelanguloA.setText("Â");

        labelanguloB.setForeground(new java.awt.Color(255, 0, 51));
        labelanguloB.setText("B^");

        labelCmLadoAB.setText("cm");

        labelCmLadoBC.setText("cm");

        labelOAnguloA.setText("º");

        labelOAnguloB.setText("º");

        labelDescubraValores.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelDescubraValores.setText("Descubra os valores abaixo:");

        labelDadosValores.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelDadosValores.setText("Dados os valores de lados do triangulo sendo: ");

        txtLadoCA.setText("0");
        txtLadoCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLadoCAActionPerformed(evt);
            }
        });

        txtAnguloC.setText("0");

        txtPerimetroP.setText("0");

        txtAreaA.setText("0");
        txtAreaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAreaAActionPerformed(evt);
            }
        });

        labelLadoCAQuiz.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelLadoCAQuiz.setText("Lado CA");

        labelAnguloCQuiz.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelAnguloCQuiz.setText("Ângulo C");

        labelPerimetroQuiz.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelPerimetroQuiz.setText("Perímetro");

        labelAreaQuiz.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelAreaQuiz.setText("Área");

        botaoProximaQuestaoQuiz.setText("Próxima Questão");
        botaoProximaQuestaoQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoProximaQuestaoQuizActionPerformed(evt);
            }
        });

        botaoTutorialQuiz.setText("Tutorial do jogo");
        botaoTutorialQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTutorialQuizActionPerformed(evt);
            }
        });

        labelAlunoQuiz.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelAlunoQuiz.setText("Aluno:");

        labelNomeAlunoQuiz.setText("NomeAluno");

        botaoSairQuiz.setText("Sair");
        botaoSairQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairQuizActionPerformed(evt);
            }
        });

        labelRespostaLadoCA.setText("jLabel6");

        labelRespostaAnguloC.setText("jLabel7");

        labelRespostaPerimetro.setText("jLabel8");

        labelRespostaArea.setText("jLabel9");

        labelDesenhoTriangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/TrianguloABC.JPG"))); // NOI18N

        labelQuestaoTexto.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        labelQuestaoTexto.setText("Questão");

        labelQuestaoNumero.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        labelQuestaoNumero.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(botaoTutorialQuiz))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(labelQuestaoTexto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelQuestaoNumero))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(labelDesenhoTriangulo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelAlunoQuiz)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelNomeAlunoQuiz))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelDadosValores)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(labelAnguloA, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(labelanguloA)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(labelOAnguloA)
                                            .addGap(18, 18, 18)
                                            .addComponent(labelAnguloB, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(labelanguloB)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(labelOAnguloB))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(labelLadoAB, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(labelladoAB)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(labelCmLadoAB)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(labelLadoBC, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(labelladoBC)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(labelCmLadoBC))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelAreaQuiz)
                                            .addComponent(labelAnguloCQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelLadoCAQuiz)
                                            .addComponent(labelPerimetroQuiz))
                                        .addGap(20, 20, 20)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtPerimetroP, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                            .addComponent(txtAnguloC)
                                            .addComponent(txtLadoCA)
                                            .addComponent(txtAreaA))
                                        .addGap(50, 50, 50)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelRespostaLadoCA)
                                            .addComponent(labelRespostaAnguloC)
                                            .addComponent(labelRespostaPerimetro)
                                            .addComponent(labelRespostaArea)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(labelDescubraValores)
                                        .addGap(90, 90, 90)))))
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(botaoSairQuiz)
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(botaoProximaQuestaoQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeAlunoQuiz)
                    .addComponent(labelAlunoQuiz))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDadosValores, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelQuestaoTexto)
                    .addComponent(labelQuestaoNumero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelLadoAB)
                            .addComponent(labelladoAB)
                            .addComponent(labelCmLadoAB)
                            .addComponent(labelLadoBC)
                            .addComponent(labelladoBC)
                            .addComponent(labelCmLadoBC))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelAnguloA)
                            .addComponent(labelanguloA)
                            .addComponent(labelOAnguloA)
                            .addComponent(labelAnguloB)
                            .addComponent(labelanguloB)
                            .addComponent(labelOAnguloB))
                        .addGap(18, 18, 18)
                        .addComponent(labelDescubraValores, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelLadoCAQuiz)
                            .addComponent(txtLadoCA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelRespostaLadoCA))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelAnguloCQuiz)
                            .addComponent(txtAnguloC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelRespostaAnguloC))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelPerimetroQuiz)
                            .addComponent(txtPerimetroP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelRespostaPerimetro)))
                    .addComponent(labelDesenhoTriangulo))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelAreaQuiz)
                            .addComponent(txtAreaA, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelRespostaArea))
                        .addGap(40, 40, 40)
                        .addComponent(botaoProximaQuestaoQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(botaoSairQuiz)
                                .addGap(23, 23, 23))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(botaoTutorialQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSairQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairQuizActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_botaoSairQuizActionPerformed

    private void botaoTutorialQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTutorialQuizActionPerformed
        new GuiTutorial().setVisible(true);
    }//GEN-LAST:event_botaoTutorialQuizActionPerformed

    private void botaoProximaQuestaoQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoProximaQuestaoQuizActionPerformed
        // TODO add your handling code here:
        auxLadoCA = Double.parseDouble(txtLadoCA.getText());
        auxAreaA = Double.parseDouble(txtAreaA.getText());
        auxPerim = Double.parseDouble(txtPerimetroP.getText());
        auxAnguloC = Double.parseDouble(txtAnguloC.getText());
        GuiInicial.setContador();
        if (GuiInicial.getContador() <= GuiInicial.getMAXIMOQUESTOES()) {
            Resultado.setResultado(auxLadoCA, auxAreaA, auxPerim, auxAnguloC);
            new GuiQuiz().setVisible(true);
            dispose();
        } else {
            Resultado.setResultado(auxLadoCA, auxAreaA, auxPerim, auxAnguloC);
            new GuiFinal().setVisible(true);
            dispose();
        }

    }//GEN-LAST:event_botaoProximaQuestaoQuizActionPerformed

    private void txtAreaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAreaAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAreaAActionPerformed

    private void txtLadoCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLadoCAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLadoCAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiQuiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoProximaQuestaoQuiz;
    private javax.swing.JButton botaoSairQuiz;
    private javax.swing.JButton botaoTutorialQuiz;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelAlunoQuiz;
    private javax.swing.JLabel labelAnguloA;
    private javax.swing.JLabel labelAnguloB;
    private javax.swing.JLabel labelAnguloCQuiz;
    private javax.swing.JLabel labelAreaQuiz;
    private javax.swing.JLabel labelCmLadoAB;
    private javax.swing.JLabel labelCmLadoBC;
    private javax.swing.JLabel labelDadosValores;
    private javax.swing.JLabel labelDescubraValores;
    private javax.swing.JLabel labelDesenhoTriangulo;
    private javax.swing.JLabel labelLadoAB;
    private javax.swing.JLabel labelLadoBC;
    private javax.swing.JLabel labelLadoCAQuiz;
    private javax.swing.JLabel labelNomeAlunoQuiz;
    private javax.swing.JLabel labelOAnguloA;
    private javax.swing.JLabel labelOAnguloB;
    private javax.swing.JLabel labelPerimetroQuiz;
    private javax.swing.JLabel labelQuestaoNumero;
    private javax.swing.JLabel labelQuestaoTexto;
    private javax.swing.JLabel labelRespostaAnguloC;
    private javax.swing.JLabel labelRespostaArea;
    private javax.swing.JLabel labelRespostaLadoCA;
    private javax.swing.JLabel labelRespostaPerimetro;
    private javax.swing.JLabel labelanguloA;
    private javax.swing.JLabel labelanguloB;
    private javax.swing.JLabel labelladoAB;
    private javax.swing.JLabel labelladoBC;
    private javax.swing.JTextField txtAnguloC;
    private javax.swing.JTextField txtAreaA;
    private javax.swing.JTextField txtLadoCA;
    private javax.swing.JTextField txtPerimetroP;
    // End of variables declaration//GEN-END:variables
}
