/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NEGOCIO.*;

/**
 *
 * @author Bernardo Gouvêa
 */
public class GuiTutorial extends javax.swing.JFrame {

    /**
     * Creates new form GuiTutorial
     */
    public GuiTutorial() {
        initComponents();
        labelNomeAlunoTutorial.setText(Avaliacao.getNome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTutorial = new javax.swing.JPanel();
        labelAlunoTutorial = new javax.swing.JLabel();
        labelNomeAlunoTutorial = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labelJogoFeitoPorTutorial = new javax.swing.JLabel();
        botaoFinalizarTutorial = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelTutorial.setBackground(java.awt.Color.white);
        panelTutorial.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 0)));
        panelTutorial.setPreferredSize(new java.awt.Dimension(650, 500));

        labelAlunoTutorial.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelAlunoTutorial.setText("Aluno:");

        labelNomeAlunoTutorial.setText("NomeAluno");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Tutorial do Jogo");

        labelJogoFeitoPorTutorial.setText("Um jogo feito por: Bernardo Gouvêa, César Barbosa, Lucas Guilhon");

        botaoFinalizarTutorial.setText("Finalizar Tutorial");
        botaoFinalizarTutorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFinalizarTutorialActionPerformed(evt);
            }
        });

        jScrollPane2.setBorder(null);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Iniciando o Quiz Trigonometria:\n     O Quiz apresentará questões para que você responda os seguintes itens:\n\n          - Dados 2 lados de um Triângulo qualquer, calcule o terceiro lado deste Triângulo.\n\n          - Dados 2 ângulos de um Triângulo qualquer, calcule o terceiro ângulo deste \nTriângulo.\n\n          - Dados 2 lados de um Triângulo qualquer, e calculado o terceiro lado anteriormente,\nencontre o Perímetro do Triângulo.\n\n          - Dados 2 lados e 2 ângulos e, calculado o terceiro lado e terceiro ângulo, encontre \na área do Triângulo.\n\n     Ao final de todas as questões respondidas, você será apresentado ao seu resultado e ao\nseu aproveitamento.\n\n     O Quiz pode ser feito quantas vezes quiser.\n     Todo resultado e aproveitamento de cada aluno será armazenado e mostrado ao\nprofessor da matéria.");
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout panelTutorialLayout = new javax.swing.GroupLayout(panelTutorial);
        panelTutorial.setLayout(panelTutorialLayout);
        panelTutorialLayout.setHorizontalGroup(
            panelTutorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTutorialLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelTutorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTutorialLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 430, Short.MAX_VALUE)
                        .addComponent(labelAlunoTutorial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelNomeAlunoTutorial)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTutorialLayout.createSequentialGroup()
                        .addGroup(panelTutorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelTutorialLayout.createSequentialGroup()
                                .addComponent(botaoFinalizarTutorial)
                                .addGap(80, 80, 80)
                                .addComponent(labelJogoFeitoPorTutorial)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(24, 24, 24))))
        );
        panelTutorialLayout.setVerticalGroup(
            panelTutorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTutorialLayout.createSequentialGroup()
                .addGroup(panelTutorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTutorialLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1))
                    .addGroup(panelTutorialLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelTutorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNomeAlunoTutorial)
                            .addComponent(labelAlunoTutorial))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(panelTutorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelJogoFeitoPorTutorial, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botaoFinalizarTutorial, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTutorial, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTutorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoFinalizarTutorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFinalizarTutorialActionPerformed
        dispose();
    }//GEN-LAST:event_botaoFinalizarTutorialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiTutorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiTutorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiTutorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiTutorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiTutorial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoFinalizarTutorial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelAlunoTutorial;
    private javax.swing.JLabel labelJogoFeitoPorTutorial;
    private javax.swing.JLabel labelNomeAlunoTutorial;
    private javax.swing.JPanel panelTutorial;
    // End of variables declaration//GEN-END:variables

}
