/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NEGOCIO.*;

/**
 *
 * @author cesar
 */
public class GuiTutorial extends javax.swing.JFrame {

    /**
     * Creates new form GuiTutorial
     */
    public GuiTutorial() {
        initComponents();
        labelNomeAlunoTutorial.setText(Avaliacao.getNome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTutorial = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaTutorialJogo = new javax.swing.JTextArea();
        labelAlunoTutorial = new javax.swing.JLabel();
        botaoSairTutorial = new javax.swing.JButton();
        labelNomeAlunoTutorial = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtAreaTutorialJogo.setColumns(20);
        txtAreaTutorialJogo.setRows(5);
        txtAreaTutorialJogo.setText("\nb) Eu vejo o problema de vocês como um Jogo que tem vários Quiz (list de quiz). Um Quiz \ntem várias instâncias de Questao. Cada Questao tem um Triangulo e as respostas do \naluno para as perguntas (área, perímetro, etc).\n\n\nd)salvando todo o Jogo (e seus respectivos objetos associados) em um único \narquivo xml que seria carregado a cada nova execução do programa.\n\n\ne) Eu vejo a parte de estatísticas do jogo como algo similar ao que está no jogo da \nortografia (represente os totais em uma classe, isolando esses totais de como eles \npodem ser apresentados em um arquivo ou em uma tela de resultado). \n\n\n");
        jScrollPane1.setViewportView(txtAreaTutorialJogo);

        labelAlunoTutorial.setText("Aluno:");

        botaoSairTutorial.setText("Finalizar Tutorial ");
        botaoSairTutorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairTutorialActionPerformed(evt);
            }
        });

        labelNomeAlunoTutorial.setText("NomeAluno");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Tutorial do Jogo");

        javax.swing.GroupLayout panelTutorialLayout = new javax.swing.GroupLayout(panelTutorial);
        panelTutorial.setLayout(panelTutorialLayout);
        panelTutorialLayout.setHorizontalGroup(
            panelTutorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTutorialLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelTutorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelTutorialLayout.createSequentialGroup()
                        .addGroup(panelTutorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoSairTutorial)
                            .addComponent(jScrollPane1))
                        .addGap(24, 24, 24))
                    .addGroup(panelTutorialLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 229, Short.MAX_VALUE)
                        .addComponent(labelAlunoTutorial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelNomeAlunoTutorial)
                        .addGap(141, 141, 141))))
        );
        panelTutorialLayout.setVerticalGroup(
            panelTutorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTutorialLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelTutorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(panelTutorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelAlunoTutorial)
                        .addComponent(labelNomeAlunoTutorial)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addGap(25, 25, 25)
                .addComponent(botaoSairTutorial)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTutorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTutorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSairTutorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairTutorialActionPerformed
        dispose();
    }//GEN-LAST:event_botaoSairTutorialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiTutorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiTutorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiTutorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiTutorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiTutorial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoSairTutorial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAlunoTutorial;
    private javax.swing.JLabel labelNomeAlunoTutorial;
    private javax.swing.JPanel panelTutorial;
    private javax.swing.JTextArea txtAreaTutorialJogo;
    // End of variables declaration//GEN-END:variables
}
